title: hyungeun Gwak
description: Web Engineer
site_title: '@grooo - hyungeun Gwak'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: abhn
blog_url: https://blog.naver.com/rgr3287
email: abhishek@nagekar.com
keybase_username: hyun
twitter_username: hyun_
reddit_username: hyun

# absolute or relative
profile_picture: assets/images/pp.jpg

# Google Analytics ID
google_analytics: 
