title: hyungeun Gwak
description: 풀스택 개발자
site_title: '@groo - hyungeun Gwak'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: abhn
blog_url: https://blog.naver.com/rgr3287
email: rgr3287@naver.com
keybase_username: hggwak
twitter_username: hggwak_
reddit_username: hggwak

# absolute or relative
profile_picture: assets/images/pp.jpg

# Google Analytics ID
google_analytics: 
