title: hyungeun Gwak
description: Web Engineer
site_title: '@grooo - hyungeun Gwak'

# Build settings
markdown: kramdown
exclude: [vendor/ruby]

# Personalization
github_username: abhn
blog_url: https://www.nagekar.com
email: rgr3287@naver.com
keybase_username: hggwak
twitter_username: hggwak
reddit_username: hggwak

# absolute or relative
profile_picture: assets/images/pp.jpg

# Google Analytics ID
google_analytics: 